<h3><?php printf(__('"%s" is a Premium feature.', 'ifw'), $this->featureName); ?></h3>

<p><?php printf( __('Check out the <a href="%s" target="_blank">Premium version</a> and all its features on CodeCanyon.', 'psn'), $this->pm->getConfig()->plugin->premiumUrl ); ?></p>

<div id="premium_ads">
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_ad_html_mails.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_ad_mailqueue.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_ad_recipients_lists.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_ad_rules.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_ad_options.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_conditional_templates.jpg" /></a>
    <a href="<?php echo $this->pm->getConfig()->plugin->premiumUrl; ?>" target="_blank"><img src="<?php echo $this->pm->getEnv()->getUrlAdminImg(); ?>/cc_extensible.jpg" /></a>
</div>