<?php wp_nonce_field($this->pm->getPathinfo()->getDirname() . '-general'); ?>
<?php wp_nonce_field('closedpostboxes', 'closedpostboxesnonce', false ); ?>
<?php wp_nonce_field('meta-box-order', 'meta-box-order-nonce', false ); ?>
<input type="hidden" name="action" value="save-<?php echo $this->pm->getPathinfo()->getDirname(); ?>-general" />

<div id="dashboard-widgets-wrap">
    <div id="dashboard-widgets" class="metabox-holder">
        <div id="postbox-container-1" class="postbox-container">
            <?php $this->metaBoxContainer1->render(); ?>
        </div>
        <div id="postbox-container-2" class="postbox-container">
            <?php $this->metaBoxContainer2->render(); ?>
        </div>
        <div id="postbox-container-3" class="postbox-container">
            <?php $this->metaBoxContainer3->render(); ?>
        </div>
        <div id="postbox-container-4" class="postbox-container">
            <?php $this->metaBoxContainer4->render(); ?>
        </div>
    </div>
</div>


<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready( function($) {
        // close postboxes that should be closed
        $('.if-js-closed').removeClass('if-js-closed').addClass('closed');
        // postboxes setup
        postboxes.add_postbox_toggles('<?php echo $this->pageHook; ?>');
    });
    //]]>
</script>


